version: '3'
services:
  docker-app:
    image: rafaeldourado50/my-app-image
    ports:
      - "8080:8080"
    depends_on:
      - docker-postgres
  docker-postgres:
    image: rafaeldourado50/my-postgres-image